import { ref, computed } from "vue";
import { defineStore } from "pinia";

export const useProductsStore = defineStore("useProducts", () => {
  const switches = ref([
    {
      id: 1,
      title: "XVR-FAX-333045N-5MP",
      img: "/1.jpg",
      optionsru: [
        "4-канальный цифровой видеорегистратор с разрешением 5 Мп.",
        "H.264/H.264+/H.265/H.265+",
        "5MP N 5 В 1. (AHD/TVI/CVI/CVBS/IP)",
        "4-КАНАЛЬНОЕ ВОСПРОИЗВЕДЕНИЕ.",
        "Поддерживает 1 жесткий диск SATA емкостью до 8 ТБ.",
        "2-канальная IP-камера @ 1080P HDMI",
        "1-канальный аналоговый звук; 2 ГБ ОЗУ; ВСПЫШКА 16М.",
        "Поддерживает ключ 3G/4G/WIFI",
        "15 кадров в секунду при 5 МП/20 кадров в секунду при 2 МП AHD/CVI/TVI",
        "25 кадров в секунду при 1080P IP",
        "По одному IP или аналоговое переключение",
        "Мобильное приложение XVRView для Android/iOS",
        "Активный быстрый P2P",
        "Сильная поддержка RTSP.",
      ],
      optionsen: [
        "4-channel digital video recorder with a resolution of 5 MP.",
        "H.264/H.264+/H.265/H.265+",
        "5MP N 5 IN 1. (AHD/TVI/CVI/CVBS/IP)",
        "4 CHANNEL PLAYBACK.",
        "Supports 1 SATA HDD up to 8 TB.",
        "2-channel IP camera @ 1080P HDMI",
        "1 channel analog audio; 2 GB RAM; FLASH 16M.",
        "Supports 3G/4G/WIFI dongle",
        "15 fps at 5 MP/20 fps at 2 MP AHD/CVI/TVI",
        "25 fps at 1080P IP",
        "One IP at a time or analog switching",
        "XVRView mobile application for Android/iOS",
        "Active fast P2P",
        "Strong RTSP support.",
      ],
      optionsuz: [
        "5 MP o'lchamli 4 kanalli raqamli video yozuvchisi.",
        "H.264/H.264+/H.265/H.265+",
        "5MP N 5 IN 1. (AHD/TVI/CVI/CVBS/IP)",
        "4 KANALLI ISHLASH.",
        "8 TB gacha bo'lgan 1 SATA HDDni qo'llab-quvvatlaydi.",
        "2 kanalli IP kamera @ 1080P HDMI",
        "1 kanalli analog audio; 2 GB RAM; FLASH 16M.",
        "3G/4G/WIFI dongle-ni qo'llab-quvvatlaydi",
        "15 kadr/s 5 MP/20 kadr/s 2 MP AHD/CVI/TVI",
        "1080P IP da 25 kadr/s",
        "Bir vaqtning o'zida bitta IP yoki analog kommutatsiya",
        "Android/iOS uchun XVRView mobil ilovasi",
        "Faol tez P2P",
        "Kuchli RTSP qo'llab-quvvatlashi.",
      ],
    },

    {
      id: 2,
      title: "XVR-FAX-333085N-5MP",
      img: "/1.jpg",
      optionsru: [
        "8-канальный цифровой видеорегистратор с разрешением 5 Мп.",
        "H.264/H.264+/H.265/H.265+",
        "5MP N 5 В 1. (AHD/TVI/CVI/CVBS/IP)",
        "8-КАНАЛЬНОЕ ВОСПРОИЗВЕДЕНИЕ.",
        "Поддерживает 1 жесткий диск SATA емкостью до 8 ТБ.",
        "8-канальная IP-камера @ 1080P",
        "Поддержка 4-канального квааксиального звука / HDMI",
        "1-канальный аналоговый звук; 2 ГБ ОЗУ; ВСПЫШКА 16М.",
        "Поддерживает ключ 3G/4G/WIFI",
        "7 кадров в секунду при 5 МП/20 кадров в секунду при  2 МП AHD/CVI/TVI",
        "25 кадров в секунду при 1080P IP",
        "По одному IP или аналоговое переключение",
        "Мобильное приложение XVRView для Android/iOS",
        "Активный быстрый P2P",
        "Сильная поддержка RTSP.",
      ],
      optionsuz: [
        "5 MP ruxsatga ega 8 kanalli raqamli video yozuvchisi.",
        "H.264/H.264+/H.265/H.265+",
        "5MP N 5 IN 1. (AHD/TVI/CVI/CVBS/IP)",
        "8 KANALLI ISHLASH.",
        "8 TB gacha bo'lgan 1 SATA HDDni qo'llab-quvvatlaydi.",
        "8 kanalli IP kamera @ 1080P",
        "4-kanalli kvaksial audio / HDMI-ni qo'llab-quvvatlaydi",
        "1 kanalli analog audio; 2 GB RAM; FLASH 16M.",
        "3G/4G/WIFI dongle-ni qo'llab-quvvatlaydi",
        "7 kadr / sekundiga 5 MP/20 kadr / 2 MP AHD/CVI/TVI",
        "1080P IP da 25 kadr/s",
        "Bir vaqtning o'zida bitta IP yoki analog kommutatsiya",
        "Android/iOS uchun XVRView mobil ilovasi",
        "Faol tez P2P",
        "Kuchli RTSP qo'llab-quvvatlashi.",
      ],
      optionsen: [
        "8-channel digital video recorder with 5 MP resolution.",
        "H.264/H.264+/H.265/H.265+",
        "5MP N 5 IN 1. (AHD/TVI/CVI/CVBS/IP)",
        "8 CHANNEL PLAYBACK.",
        "Supports 1 SATA HDD up to 8 TB.",
        "8-channel IP camera @ 1080P",
        "Supports 4-channel quaaxial audio / HDMI",
        "1 channel analog audio; 2 GB RAM; FLASH 16M.",
        "Supports 3G/4G/WIFI dongle",
        "7 fps at 5 MP/20 fps at 2 MP AHD/CVI/TVI",
        "25 fps at 1080P IP",
        "One IP at a time or analog switching",
        "XVRView mobile application for Android/iOS",
        "Active fast P2P",
        "Strong RTSP support.",
      ],
    },

    {
      id: 3,
      title: "XVR-FAX-333165N-5MP",
      img: "/1.jpg",
      optionsru: [
        "16-канальный цифровой видеорегистратор с разрешением 5 Мп.",
        "H.264/H.264+/H.265/H.265+",
        "5MP N 5 В 1. (AHD/TVI/CVI/CVBS/IP)",
        "16-КАНАЛЬНОЕ ВОСПРОИЗВЕДЕНИЕ.",
        "Поддерживает 2 жестких диска SATA емкостью до 8 ТБ.",
        "16-канальная IP-камера @ 1080P",
        "HDMI/2-канальный аналоговый звук; 2 ГБ ОЗУ; ВСПЫШКА 16М.",
        "Поддерживает ключ 3G/4G/WIFI",
        "6 кадров в секунду при 5 МП/20 кадров в секунду при 2 МП AHD/CVI/TVI",
        "25 кадров в секунду при 1080P IP",
        "По одному IP или аналоговое переключение",
        "Мобильное приложение XVRView для Android/iOS",
        "Активный быстрый P2P",
        "Сильная поддержка RTSP.",
      ],
      optionsen: [
        "16-channel digital video recorder with a resolution of 5 MP.",
        "H.264/H.264+/H.265/H.265+",
        "5MP N 5 IN 1. (AHD/TVI/CVI/CVBS/IP)",
        "16 CHANNEL PLAYBACK.",
        "Supports 2 SATA hard drives up to 8 TB.",
        "16-channel IP camera @ 1080P",
        "HDMI/2-channel analog audio; 2 GB RAM; FLASH 16M.",
        "Supports 3G/4G/WIFI dongle",
        "6 fps at 5 MP/20 fps at 2 MP AHD/CVI/TVI",
        "25 fps at 1080P IP",
        "One IP at a time or analog switching",
        "XVRView mobile application for Android/iOS",
        "Active fast P2P",
        "Strong RTSP support.",
      ],
      optionsuz: [
        "16-kanalnyy tsifrovoy videoregistrator s razresheniem 5 Mp.",
        "H.264/H.264+/H.265/H.265+",
        "5MP N 5 V 1. (AHD/TVI/CVI/CVBS/IP)",
        "16-KANALNOE VASPROIZVEDENIE.",
        "Podderjivaet 2 jestkix disk SATA 8 TB gacha",
        "16-kanalli IP-kamera @ 1080P",
        "HDMI/2-kanalnyy analogovyy zvuk; 2 GB OZU; VSPYSHKA 16M.",
        "Podderjivaet klyuch 3G/4G/WIFI",
        "6 kadrov v sekund 5 MP/20 kadrov v sekund 2 MP AHD/CVI/TVI",
        "1080P IP uchun 25 kadrov v soniya",
        "Po odnomu IP yoki analogovoe pereklyuchenie",
        "Android/iOS uchun XVRView mobil moslamasi",
        "Activnyy bystryy P2P",
        "Silnaya podderjka RTSP.",
      ],
    },

    {
      id: 4,
      title: "NVR- FIN-333644K– 4K",
      img: "/2.jpg",
      optionsru: [
        "64 канала: поддержка полного подключения 64-канальной камеры 4K (8,0​ МП)​",
        "Поддержка быстрого переключения многосценических режимов камер IPC.​",
        "Автоматическое добавление камер + автоматическое переключение на H.265.​",
        "Поддержка межсегментного поиска и добавления камер.​",
        "Полная совместимость: поддержка основного бренда и основногопроизводителя IPC.​",
        "доступ к модулю;​",
        "Поддержка изменения параметров изображения: насыщенность, яркость,  контрастность и т. д.​",
        "Поддержка изменения параметров кодирования IPC;​",
        "Поддержка технологии интеллектуального сжатия кодирования CODE​",
        "патентов UOS,​",
        "сокращение объема хранилища вдвое и уменьшение вдвое, а также экономия  места на жестком диске с помощью Super H.265;​",
        "Поддержка изменения информации OSD основных поставщиков IPC;​",
        "Поддержка перетаскивания мышью для изменения канала камеры и  синхронного изменения.​",
        "соответствующий канал воспроизведения видео;​",
        "Поддержка функций сигнализации, таких как отключение проводов;​",
        "Поддержка видеоформатов Ultra 265/H.265/H.264H​",
        "IP-камеры сторонних производителей, поддерживающие соответствие​",
        "ONVIF.​",
        "Входная полоса пропускания: до 320 Мбит/с.​",
        "возможность воспроизведения 16*1080p@30  8*4МП@30​",
        "4*4к@30​",
        "приложение Guard Viewer CMS: GUARD STATHON​",
        "разрешение записи​",
        "Поддержка 1 канала HDMI, 1 канала VGA (5) Одновременная поддержка​",
        "HDMI и VGA​",
        "4 жестких диска SATA до 10 ТБ​",
        "Поддержка обновления облака",
      ],
      optionsen: [
        "64 channels: support for full podklucheniya 64-channel camera 4K (8.0 MP)",
        "Podderzka bystrogo pereklyuchenia mnogostsenicheskikh regime kamer IPC.​",
        "Automatic addition of camera + automatic switching on H.265.​",
        "Podderzhka mejsegmentnogo poiska i dobavleniya kamer.​",
        "Polnaya sovmestimost: podderzka osnogo nogo brand i osnogogoproizvoditelya IPC.​",
        "dostup k moduliu;",
        "Podderzka izmeneniya parameters izbrazheniya: nasyshchennost, yarkost, kontrastnost i t. d.",
        "Podderzka izmenenia parameter kodirovaniya IPC;",
        "Support technology of intellectual coding code",
        "patentov UOS,​",
        "sokrashchenie obema xranilishcha vdvoe i umenshenie vdvoe, a takje ekonomiya mesta na jestkom diske s pomoshchyu Super H.265;",
        "Poderzka izmeneniya informatsii OSD osnovnykh postavshchikov IPC;",
        "Mouse drag support for changing the camera channel and synchronizing change.​",
        "sootvetstvuyushchi channel vosproizvedeniya video;​",
        "Podderzka functional signaling, takikh kak otklyuchenie provodov;",
        "Podderjka videoformatov Ultra 265/H.265/H.264H",
        "IP camera proizvoditeley, podderjivayushchie sootvetstvie",
        "ONVIF.",
        "Input bandwidth: up to 320 Mbit/s",
        "vozmojnost vosproizvedeniya 16*1080p@30 8*4MP@30",
        "4*4k@30",
        "privilege Guard Viewer CMS: GUARD STATHON",
        "resolution record",
        "Support 1 channel HDMI, 1 channel VGA (5) Odnovremennaya podderjka​",
        "HDMI and VGA",
        "4 hard drives SATA do 10 TB",
        "Podderzka obnovleniya oblaka",
      ],
      optionsuz: [
        "64 kanal: podderjka polnogo podklyucheniya 64 kanalli kamera 4K (8,0 MP)​",
        "Podderjka bystrogo pereklyucheniya mnogoscenicheskix rejim kamerasi IPC.​",
        "Avtomatik dobavlenie kamera + H.265 uchun avtomatik pereklyuchenie",
        "Podderjka mejsegmentnogo poiska va dobavleniya kamer.​",
        "Polnaya sovmestimost: podderjka osnovnogo brenda va osnovnogoproizvoditelya IPC.​",
        "dostu k modulu;​",
        "Podderjka izmeneniya parametrov izobrajeniya: nasyshchennost, yarkost, kontrastnost va t. d.​",
        "Podderjka izmeneniya parametrov kodirovaniya IPC;​",
        "Podderjka texnologii intellektualnogo sjatiya kodrovaniya CODE​",
        "patentov UOS,",
        "sokrashchenie ob'ema xranilishcha vdvoe i umenshenie vdvoe, a ham ekonomiya mesta na jestkom diske s pomoshchyu Super H.265;​",
        "Podderjka izmeneniya informatsii OSD osnovnyx postavshchikov IPC;​",
        "Podderjka peretaskivaniya myshyu uchun izmeneniya kanal kamerasi va sinxronnogo izmeneniya.​",
        "sootvetstvuyushchiy kanal vosproizvedeniya video;​",
        "Podderjka funktsiya signalizatsii, shuningdek, qanday otklyuchenie provodov;​",
        "Podderjka videoformatov Ultra 265/H.265/H.264H​",
        "IP-kamery storonnix proizvoditeley, podderjivayushchie sootvetstvie",
        "ONVIF.",
        "Vxodnaya polosa propuskaniya: 320 Mbit/s. gacha",
        "vozmojnost vosproizvedeniya 16*1080p@30 8*4MP@30​",
        "4*4k@30​",
        "prilojenie Guard Viewer CMS: GUARD STATHON​",
        "razreshenie zapisi",
        "Podderjka 1 kanala HDMI, 1 kanal VGA (5) Odnovremennaya podderjka​",
        "HDMI va VGA",
        "4 ta disk SATA dan 10 TB gacha",
        "Podderjka obnovleniya oblaka",
      ],
    },

    {
      id: 5,
      title: "NVR- FIN-333324K– 4K",
      img: "/2.jpg",
      optionsru: [
        "32 канала: поддержка полного подключения 32-канальной камеры 4K (8,0 МП);​",
        "Поддержка быстрого переключения многосценических режимов камер IPC;​",
        "Автоматическое добавление камер;​",
        "Поддержка межсегментного поиска и добавление камер: добавление основных  брендов и Модули IPC для межсегментного поиска;​",
        "Поддержка изменения IP-адреса, даже IP-адреса других марок IPC;​",
        "Полная совместимость: поддержка основного бренда и основного  производителя IPC.​",
        "доступ к модулю;​",
        "Поддержка изменения параметров изображения: насыщенность, яркость,  контрастность и т. д.​",
        "Поддержка изменения параметров кодирования IPC;​",
        "Поддержка технологии интеллектуального сжатия кодирования CODE патентов UOS​",
        "сокращение объема хранилища вдвое и уменьшение вдвое, а также экономия  места на жестком диске с помощью Super H.265;​",
        "Поддержка изменения информации OSD основных поставщиков IPC;​",
        "Поддержка перетаскивания мышью для изменения канала камеры и  синхронного изменения.​",
        "соответствующий канал воспроизведения видео;​",
        "Поддержка функций сигнализации, таких как отключение проводов;​",
        "Поддержка 32-канального интерфейса для обеспечения одинакового размера  изображения дороги при 20-канальном полном воспроизведении;​",
        "Приложение UFO GV (GUARD VIEWER) представляет собой динамичную карту  без рекламы.​",
        "Хранение без сбоев: Universal Vision имеет технологию хранения,  автоматическое форматирование жесткого диска без потери видео.​",
        "Он также поддерживает функцию обнаружения плохих дорожек и экранирования  жесткого диска Western.​",
        "во избежание повреждения жесткого диска, вызванного распространением  плохой дорожки.",
      ],
      optionsuz: [
        "32 kanal: podderjka polnogo podklyucheniya 32-kanalli kamera 4K (8,0 MP);​",
        "Podderjka bystrogo pereklyucheniya mnogoscenicheskix rejim kamerasi IPC;​",
        "Avtomaticeskoe dobavlenie kamer;​",
        "Podderjka mejsegmentnogo poiska va dobavlenie kamer: dobavlenie osnovnyx brendov va Moduli IPC uchun mejsegmentnogo poiska;​",
        "Podderjka izmeneniya IP-adres, yoki IP-manzil dorix maroq IPC;​",
        "Polnaya sovmestimost: podderjka osnovnogo brenda va osnovnogo proizvoditelya IPC.​",
        "dostu k modulu;​",
        "Podderjka izmeneniya parametrov izobrajeniya: nasyshchennost, yarkost, kontrastnost va t. d.​",
        "Podderjka izmeneniya parametrov kodirovaniya IPC;​",
        "Podderjka texnologii intellektualnogo sjatia kodirovaniya CODE patentov UOS​",
        "sokrashchenie ob'ema xranilishcha vdvoe i umenshenie vdvoe, a ham ekonomiya mesta na jestkom diske s pomoshchyu Super H.265;​",
        "Podderjka izmeneniya informatsii OSD osnovnyx postavshchikov IPC;​",
        "Podderjka peretaskivaniya myshyu uchun izmeneniya kanal kamerasi va sinxronnogo izmeneniya.​",
        "sootvetstvuyushchiy kanal vosproizvedeniya video;​",
        "Podderjka funktsiya signalizatsii, shuningdek, qanday otklyuchenie provodov;​",
        "Podderjka 32-kanalnogo interfeysi uchun obespecheniya odinakovo razmera izobrajeniya dorogi pri 20-kanalnom polnom vosproizvedenii;​",
        "Prilojenie UFO GV (GUARD VIEWER) soboy dinamichnuyu kartasiz reklama qiladi.​",
        "Xranenie bez sboev: Universal Vision imeet texnologiyu xraneniya, avtomatlashtirilgan formatlashtirish jestkogo diska bez poteri video.​",
        "Bunday podderjivaet funksiyasi obnarujeniya ploxix dojek va ekranirovaniya jestkogo diska Western.​",
        "vo izbejanie povrejdeniya jestkogo diska, vyzvannogo rasprostraneniem plohoy dorojki.",
      ],
      optionsen: [
        "32 channels: support for full podklucheniya 32-channel camera 4K (8.0 MP);",
        "Podderzka bystrogo pereklyuchenia mnogostsenicheskikh regime kamer IPC;",
        "Automatic addition of camera;",
        "Podderzka mejsegmentnogo poiska and adding cameras: adding basic brands and Moduli IPC for mejsegmentnogo poiska;",
        "Podderzka change IP-address, even IP-address second time IPC;",
        "Polnaya sovmestimost: support of the basic brand and the basic product of IPC.​",
        "dostup k moduliu;",
        "Podderzka izmeneniya parameters izbrazheniya: nasyshchennost, yarkost, kontrastnost i t. d.",
        "Podderzka izmenenia parameter kodirovaniya IPC;",
        "Podderzhka tekhnologii intellectualnogo shjatiya kodirovaniya CODE patents UOS",
        "sokrashchenie obema xranilishcha vdvoe i umenshenie vdvoe, a takje ekonomiya mesta na jestkom diske s pomoshchyu Super H.265;",
        "Poderzka izmeneniya informatsii OSD osnovnykh postavshchikov IPC;",
        "Mouse drag support for changing the camera channel and synchronizing change.​",
        "sootvetstvuyushchi channel vosproizvedeniya video;​",
        "Podderzka functional signaling, takikh kak otklyuchenie provodov;",
        "Support for a 32-channel interface to ensure the same size of the image in 20-channel full production;",
        "Prilozhenie UFO GV (GUARD VIEWER) predstavlyaet soboy dinamichnyu kartu without advertising.​",
        "Hranenie bez boev: Universal Vision has technology of hranenia, automatic formatting of a jestkogo disk without poteri video.​​",
        "On takje podderjivaet funksiyu obnaruzheniya flat dorojek i ekrinirovaniya jestkogo disko Western.​​",
        "vo izbejanie pvrejdeniya jestkogo diska, vyzvannogo rasprostranienim bad dorojki.",
      ],
    },

    {
      id: 6,
      title: "NVR- FIN-333165 - 5MP",
      img: "/2.jpg",
      optionsru: [
        "H.264/H.264+/H.265​",
        "16 каналов: поддержка полного подключения 16-канальной камеры 5,0 МП; Поддержка быстрого переключения многосценовых режимов IPC-камер;  Автоматическое добавление камер​",
        "Поддержка межсегментного поиска и добавление камер: добавление  основных брендов и модулей IPC в межсегментный поиск;​",
        "Поддержка изменения IP-адреса, даже IP-адреса других марок IPC;​",
        "Полная совместимость: поддержка доступа к модулю IPC основного бренда и  основного производителя;​",
        "Поддержка изменения параметров изображения: насыщенность, яркость,  контрастность и т. д.​",
        "Поддержка изменения параметров кодирования IPC;​",
        "Поддержка технологии интеллектуального сжатия кодирования CODE,​",
        "запатентованной патентами UOS, сокращение объема памяти вдвое и  уменьшение вдвое, а также экономия места на жестком диске с помощью  Super H.265;​",
        "Поддержка изменения информации OSD IPC;​",
        "Поддержка перетаскивания мышью для изменения канала камеры и​",
        "синхронного изменения соответствующего канала воспроизведения видео;  Поддержка функций сигнализации, таких как отключение проводов;​",
        "Поддержка 16-канального интерфейса для обеспечения одинакового размера  изображения дороги при 10-канальном полном воспроизведении;​",
        "Приложение UFO GV (GUARD VIEWER) представляет собой динамичную карту  без рекламы.​",
        "Хранение без сбоев: Universal Vision имеет технологию хранения,​",
        "автоматическое форматирование жесткого диска, отсутствие потери видео. Он  также поддерживает функцию обнаружения и защиты плохих дорожек​",
        "жесткого диска Western, чтобы избежать повреждения жесткого диска,  вызванного распространением плохих дорожек.​",
      ],
      optionsen: [
        "H.264/H.264+/H.265​",
        "16 channels: support full connection of 16-channel 5.0 MP camera; Support fast switching of multi-scene modes of IPC cameras; Automatic addition of cameras​",
        "Support for cross-segment search and adding cameras: adding major brands and IPC modules to cross-segment search;​",
        "Supports changing the IP address, even the IP address of other IPC brands;​",
        "Full Compatibility: Supports access to major brand and major manufacturer IPC module;​",
        "Support for changing image parameters: saturation, brightness, contrast, etc.​",
        "Support for changing IPC encoding parameters;​",
        "Support for intelligent coding compression technology CODE,​",
        "patented UOS, halve memory size, halve size, and save hard drive space with Super H.265;​",
        "Support changing OSD IPC information;​",
        "Supports drag-and-drop to change camera channel and​",
        "synchronously changes the corresponding video playback channel; Supports alarm functions such as cutting off wires;",
        "Supports 16-channel interface to ensure the same road image size in 10-channel full playback;​",
        "The UFO GV (GUARD VIEWER) app is a dynamic map without ads.​",
        "Storage without interruption: Universal Vision has storage technology,",
        "automatic hard disk formatting, no video loss. It also supports bad track detection and protection function",
        "Western hard drive to avoid hard drive damage caused by bad tracks spreading.​",
      ],
      optionsuz: [
        "H.264/H.264+/H.265",
        "16 kanal: 16 kanalli 5,0 MP kameraning to'liq ulanishini qo'llab-quvvatlaydi; IPC kameralarining ko'p sahnali rejimlarini tez almashtirishni qo'llab-quvvatlash; Kameralarni avtomatik qo'shish",
        "Kross-segmentlarni qidirish va kameralarni qo'shishni qo'llab-quvvatlash: segmentlararo qidiruvga asosiy brendlar va IPC modullarini qo'shish;​",
        "IP manzilini, hatto boshqa IPC brendlarining IP manzilini o'zgartirishni qo'llab-quvvatlaydi;​",
        "To'liq moslik: asosiy brend va yirik ishlab chiqaruvchi IPC moduliga kirishni qo'llab-quvvatlaydi;​",
        "Tasvir parametrlarini o'zgartirishni qo'llab-quvvatlash: to'yinganlik, yorqinlik, kontrast va boshqalar",
        "IPC kodlash parametrlarini o'zgartirishni qo'llab-quvvatlash;​",
        "CODE aqlli kodlashni siqish texnologiyasini qo'llab-quvvatlash,",
        "Super H.265 bilan patentlangan UOS, xotira hajmini ikki baravar kamaytiring, oʻlchamini ikki baravar kamaytiring va qattiq diskdagi joyni saqlang;​",
        "OSD IPC ma'lumotlarini o'zgartirishni qo'llab-quvvatlash;​",
        "Kamera kanalini o'zgartirish uchun sudrab tashlashni qo'llab-quvvatlaydi va",
        "mos videoni ijro etish kanalini sinxron ravishda o'zgartiradi; simlarni uzish kabi signal funktsiyalarini qo'llab-quvvatlaydi;",
        "10 kanalli to'liq ijroda yo'l tasvirining bir xil o'lchamini ta'minlash uchun 16 kanalli interfeysni qo'llab-quvvatlaydi;​",
        "NUJ GV (GUARD VIEWER) ilovasi reklamasiz dinamik xaritadir.​",
        "Uzluksiz saqlash: Universal Vision saqlash texnologiyasiga ega",
        "Qattiq diskni avtomatik formatlash, video yo'qotish yo'q. Shuningdek, yomon treklarni aniqlash va himoya qilish funksiyasini qo'llab-quvvatlaydi",
        "G'arbiy qattiq disk noto'g'ri yo'llarning tarqalishi natijasida qattiq disk shikastlanishining oldini olish uchun.",
      ],
    },
  ]);

  const cameras = ref([
    {
      id: 7,
      img: "./3.jpg",
      title: "5mp FIB-S1084k5 5mp",
      optionspr: [
        "دوربین گنبدی فلزی",
        "تصویربرداری با کیفیت بالا با وضوح 5 مگاپیکسل",
        "تصویربرداری رنگارنگ 24 ساعته",
        "5 مگاپیکسل Super Starlight Progressive Scan CMOS",
        "پشتیبانی از 120 دسی بل پویا عرض نوری (WDR) دو میکروفون",
        "رزولوشن 5 مگاپیکسلی HD، 2880*1620@25، 2560*1440@25، 2304*1296@25، 1920*1080@25، 1920*1080@30",
        "پشتیبانی از تشخیص بدن انسان + عملکرد هوشمند دو نوری،",
        "کنترل هوشمند مادون قرمز/نور گرم، بدون نیاز به حساسیت به نور",
        "پشتیبانی از کدگذاری هوشمند Ultra H. 265",
        "پشتیبانی از پروتکل استاندارد بین المللی Onvif با NVR شخص ثالث، پشتیبانی از Uniview و پروتکل خصوصی HIK Vision",
        "پشتیبانی از ورودی/خروجی صوتی 1ch، پشتیبانی از صدای دو طرفه؛ اگر به این گزینه نیاز دارید، باید آن را سفارش دهید",
        "نور ستاره: روز/شب (ICR) AWB، AGC، BLC، HLC2DNR/3DNR",
        "چراغ هیبریدی هوشمند: فناوری پیشرفته با برد طولانی",
        "LENZ: لنز کانونی ثابت 4mm",
        "مقاوم در برابر آب و گرد و غبار (IP66)",
        "SMATR POE",
      ],
      optionsen: [
        "METAL DOME CAMERA",
        "High quality imaging with 5 MP resolution",
        "24/7 colorful imaging",
        "5MP Super Starlight   Progressive Scan CMOS",
        "Support 120dB Optical width dynamic (WDR) two mic",
        "5MP HD Resolution, 2880*1620@25, 2560*1440@25, 2304*1296@25, 1920*1080@25, 1920*1080@30",
        "Support Human Body Detection + Dual-Light Intelligent Function,",
        "Smart infrared/warm light control, no need photosensitive",
        "Supports Ultra H. 265 intelligent coding",
        "Support Onvif international standard protocol with third-party NVR, Support Uniview and HIK Vision private protocol",
        "Support audio input/output 1ch, support two-way audio;Если вам нужна эта опция, вы должны заказать ее",
        "Starlight :Day/Night (ICR) AWB,AGC,BLC,HLC2DNR/3DNR",
        "Smart Hybrid Light: advanced technology with long range",
        "LENZ:4mm fixed focal lens",
        "Water and dust resistant (IP66)",
        "SMATR POE",
      ],
      optionsuz: [
        "METAL gumbazli kamera",
        "5 MP ruxsati bilan yuqori sifatli tasvirlash",
        "24/7 rangli tasvir",
        "5MP Super Starlight Progressive Scan CMOS",
        "120dB Optik kenglik dinamikasi (WDR) ikkita mikrofonni qo'llab-quvvatlash",
        "5MP HD ruxsati, 2880*1620@25, 2560*1440@25, 2304*1296@25, 1920*1080@25, 1920*1080@30",
        "Inson tanasini aniqlashni qo'llab-quvvatlash + Ikki nurli aqlli funktsiya,",
        "Aqlli infraqizil/issiq yorug'lik nazorati, fotosensitivlik kerak emas",
        "Ultra H. 265 aqlli kodlashni qo'llab-quvvatlaydi",
        "Onvif xalqaro standart protokolini uchinchi tomon NVR, Support Uniview va HIK Vision shaxsiy protokoli bilan qo'llab-quvvatlash",
        "1 kanalli audio kirish/chiqishni qo'llab-quvvatlang, ikki tomonlama audioni qo'llab-quvvatlang; Agar sizga ushbu parametr kerak bo'lsa, uni buyurtma qilishingiz kerak",
        "Yulduzli yorug'lik: Kunduz/Kecha (ICR) AWB, AGC, BLC, HLC2DNR/3DNR",
        "Smart Hybrid Light: uzoq masofali ilg'or texnologiya",
        "LENZ: 4 mm qattiq fokusli linza",
        "Suv va changga chidamli (IP66)",
        "SMATR POE",
      ],
      optionsru: [
        "МЕТАЛЛОКУПОЛЬНАЯ КАМЕРА",
        "Высококачественное изображение с разрешением 5 МП",
        "Цветное изображение 24 часа в сутки, 7 дней в неделю",
        "5 МП Super Starlight CMOS с прогрессивной разверткой",
        "Поддержка двух микрофонов с оптической шириной 120 дБ (WDR)",
        "Разрешение HD 5 МП, 2880*1620@25, 2560*1440@25, 2304*1296@25, 1920*1080@25, 1920*1080@30",
        "Поддержка обнаружения человеческого тела + интеллектуальная функция двойного освещения",
        "Интеллектуальное управление инфракрасным/теплым светом, нет необходимости в светочувствительности",
        "Поддержка интеллектуального кодирования Ultra H. 265",
        "Поддержка международного стандартного протокола Onvif со сторонними видеорегистраторами, поддержка частного протокола Uniview и HIK Vision",
        "Поддержка 1-канального аудиовхода/вывода, поддержка двусторонней аудиосвязи; если вам нужна эта опция, вы должны заказать ее",
        "Звездный свет: день/ночь (ICR) AWB,AGC,BLC,HLC2DNR/3DNR",
        "Умный гибридный свет: передовые технологии с большим радиусом действия",
        "ЛЕНЦ: объектив с фиксированным фокусным расстоянием 4 мм",
        "Водо- и пыленепроницаемость (IP66)",
        "СМАТР ПОЭ",
      ],
    },

    {
      id: 8,
      img: "./3.jpg",
      title: "4mp FIB-S1084k334 4mp",
      optionsen: [
        "METAL DOME CAMERA",
        "High quality imaging with 4 MP resolution",
        "24/7 colorful imaging",
        "Support Human Body Detection + Dual-Light Intelligent Function,",
        "4mp hd resolution, 2560*1440@25, 2304*1296@25 , 1080P@25",
        "Smart infrared/warm light control, no need photosensitive",
        "Supports Ultra H. 265 intelligent coding",
        "Support Onvif international standard protocol",
        "Support audio input/output 1ch, support two-way audio;support dual-stream Если вам нужна эта опция, вы должны заказать ее",
        "Smart Hybrid Light: advanced technology with long range",
        "LENZ:4mm fixed focal lens",
        "Water and dust resistant (IP66)",
        "SMATR POE",
      ],
      optionsru: [
        "МЕТАЛЛОКУПОЛЬНАЯ КАМЕРА",
        "Высококачественное изображение с разрешением 4 МП",
        "Цветное изображение 24 часа в сутки, 7 дней в неделю",
        "Поддержка обнаружения человеческого тела + интеллектуальная функция двойного освещения",
        "Разрешение HD 4 Мп, 2560*1440@25, 2304*1296@25, 1080P@25",
        "Интеллектуальное управление инфракрасным/теплым светом, нет необходимости в светочувствительности",
        "Поддержка интеллектуального кодирования Ultra H. 265",
        "Поддержка международного стандартного протокола Onvif",
        "Поддержка 1-канального аудиовхода/вывода, поддержка двустороннего звука; поддержка двухпотокового звука. Если вам нужна эта опция, вы должны ее заказать",
        "Умный гибридный свет: передовые технологии с большим радиусом действия",
        "ЛЕНЦ: объектив с фиксированным фокусным расстоянием 4 мм",
        "Водо- и пыленепроницаемость (IP66)",
        "СМАТР ПОЭ",
      ],
      optionsuz: [
        "METAL gumbazli kamera",
        "4 MP ruxsati bilan yuqori sifatli tasvirlash",
        "24/7 rangli tasvir",
        "Inson tanasini aniqlashni qo'llab-quvvatlash + Ikki nurli aqlli funktsiya,",
        "4mp hd ruxsati, 2560*1440@25, 2304*1296@25, 1080P@25",
        "Aqlli infraqizil/issiq yorug'lik nazorati, fotosensitivlik kerak emas",
        "Ultra H. 265 aqlli kodlashni qo'llab-quvvatlaydi",
        "Onvif xalqaro standart protokolini qo'llab-quvvatlash",
        "1 kanalli audio kirish/chiqishni qo'llab-quvvatlash, ikki tomonlama audioni qo'llab-quvvatlash; ikki tomonlama oqimni qo'llab-quvvatlash, agar kerak bo'lsa, bu variant, albatta, buyurtma berish",
        "Smart Hybrid Light: uzoq masofali ilg'or texnologiya",
        "LENZ: 4 mm qattiq fokusli linza",
        "Suv va changga chidamli (IP66)",
        "SMATR POE",
      ],
    },

    {
      id: 9,
      img: "./3.jpg",
      title: "4mp FIB-S1084k414 4mp",
      optionsen: [
        "METAL DOME CAMERA",
        "High quality imaging with 4 MP resolution",
        "24/7 colorful imaging",
        "Flash 8MB,DDR264MB ; single-core A7 1.2GHz",
        "Support Human Body Detection + Dual-Light Intelligent Function,",
        "4mp hd resolution, 2560*1440@25, 2304*1296@25 , 1080P@25",
        "Smart infrared/warm light control, no need photosensitive",
        "Supports Ultra H. 265 intelligent coding*Support Onvif international standard protocol with third-party NVR, Support Uniview and HIK Vision private protocol",
        "Support audio input/output 1ch, support two-way audio;",
        "LENZ:4mm fixed focal lens",
        "Water and dust resistant (IP66)",
        "SMATR POE",
      ],
      optionsru: [
        "МЕТАЛЛОКУПОЛЬНАЯ КАМЕРА",
        "Высококачественное изображение с разрешением 4 МП",
        "Цветное изображение 24 часа в сутки, 7 дней в неделю",
        "Флэш-память 8 МБ, DDR264 МБ; одноядерный A7 1,2 ГГц",
        "Поддержка обнаружения человеческого тела + интеллектуальная функция двойного освещения",
        "Разрешение HD 4 Мп, 2560*1440@25, 2304*1296@25, 1080P@25",
        "Интеллектуальное управление инфракрасным/теплым светом, нет необходимости в светочувствительности",
        "Поддержка интеллектуального кодирования Ultra H. 265 * Поддержка протокола международного стандарта Onvif со сторонними видеорегистраторами, поддержка частного протокола Uniview и HIK Vision",
        "Поддержка аудиовхода/выхода 1 канал, поддержка двустороннего звука;",
        "ЛЕНЦ: объектив с фиксированным фокусным расстоянием 4 мм",
        "Водо- и пыленепроницаемость (IP66)",
        "СМАТР ПОЭ",
      ],
      optionsuz: [
        "METAL gumbazli kamera",
        "4 MP ruxsati bilan yuqori sifatli tasvirlash",
        "24/7 rangli tasvir",
        "Flash 8MB, DDR264MB; bir yadroli A7 1.2GHz",
        "Inson tanasini aniqlashni qo'llab-quvvatlash + Ikki nurli aqlli funktsiya,",
        "4mp hd ruxsati, 2560*1440@25, 2304*1296@25, 1080P@25",
        "Aqlli infraqizil/issiq yorug'lik nazorati, fotosensitivlik kerak emas",
        "Ultra H. 265 aqlli kodlashni qo'llab-quvvatlaydi* Onvif xalqaro standart protokolini uchinchi tomon NVR, Support Uniview va HIK Vision shaxsiy protokoli bilan qo'llab-quvvatlaydi",
        "1 kanalli audio kirish/chiqishni qo'llab-quvvatlash, ikki tomonlama ovozni qo'llab-quvvatlash;",
        "LENZ: 4 mm qattiq fokusli linza",
        "Suv va changga chidamli (IP66)",
        "SMATR POE",
      ],
    },

    {
      id: 10,
      img: "./4.jpg",
      title: "5mp FID-S1087k5 5mp",
      optionsen: [
        "METAL BULLET CAMERA",
        "High quality imaging with 5 MP resolution",
        "24/7 colorful imaging",
        "5MP Super Starlight   Progressive Scan CMOS",
        "Support 120dB Optical width dynamic (WDR)   ",
        "two mic",
        "5MP HD Resolution, 2880*1620@25, 2560*1440@25, 2304*1296@25, 1920*1080@25, 1920*1080@30",
        "Support Human Body Detection + Dual-Light Intelligent Function,",
        "Smart infrared/warm light control, no need photosensitive",
        "Supports Ultra H. 265 intelligent coding",
        "Support Onvif international standard protocol with third-party NVR, Support Uniview and HIK Vision private protocol",
        "Support audio input/output 1ch, support two-way audio;",
        "Starlight :Day/Night(ICR)AWB,AGC,BLC,HLC2DNR/3DNR",
        "Smart Hybrid Light: advanced technology with long range",
        "LENZ:4mm fixed focal lens",
        "Water and dust resistant (IP66)",
        "SMATR POE",
      ],
      optionsru: [
        "МЕТАЛЛ ПУЛЯ КАМЕРА",
        "Высококачественное изображение с разрешением 5 МП",
        "Цветное изображение 24 часа в сутки, 7 дней в неделю",
        "5 МП Super Starlight CMOS с прогрессивной разверткой",
        "Поддержка динамической оптической ширины 120 дБ (WDR)",
        "два микрофона",
        "Разрешение HD 5 МП, 2880*1620@25, 2560*1440@25, 2304*1296@25, 1920*1080@25, 1920*1080@30",
        "Поддержка обнаружения человеческого тела + интеллектуальная функция двойного освещения",
        "Интеллектуальное управление инфракрасным/теплым светом, нет необходимости в светочувствительности",
        "Поддержка интеллектуального кодирования Ultra H. 265",
        "Поддержка международного стандартного протокола Onvif со сторонними видеорегистраторами, поддержка частного протокола Uniview и HIK Vision",
        "Поддержка аудиовхода/выхода 1 канал, поддержка двустороннего звука;",
        "Звездный свет: день/ночь (ICR)AWB,AGC,BLC,HLC2DNR/3DNR",
        "Умный гибридный свет: передовые технологии с большим радиусом действия",
        "ЛЕНЦ: объектив с фиксированным фокусным расстоянием 4 мм",
        "Водо- и пыленепроницаемость (IP66)",
        "СМАТР ПОЭ",
      ],
      optionsuz: [
        "METAL BULLET KAMERA",
        "5 MP ruxsati bilan yuqori sifatli tasvirlash",
        "24/7 rangli tasvir",
        "5MP Super Starlight Progressive Scan CMOS",
        "120dB Optik kenglik dinamikini (WDR) qo'llab-quvvatlash",
        "ikki mikrofon",
        "5MP HD ruxsati, 2880*1620@25, 2560*1440@25, 2304*1296@25, 1920*1080@25, 1920*1080@30",
        "Inson tanasini aniqlashni qo'llab-quvvatlash + Ikki nurli aqlli funktsiya,",
        "Aqlli infraqizil/issiq yorug'lik nazorati, fotosensitivlik kerak emas",
        "Ultra H. 265 aqlli kodlashni qo'llab-quvvatlaydi",
        "Onvif xalqaro standart protokolini uchinchi tomon NVR, Support Uniview va HIK Vision shaxsiy protokoli bilan qo'llab-quvvatlash",
        "1 kanalli audio kirish/chiqishni qo'llab-quvvatlash, ikki tomonlama ovozni qo'llab-quvvatlash;",
        "Yulduzli yorug'lik: kunduz / tun (ICR) AWB, AGC, BLC, HLC2DNR / 3DNR",
        "Smart Hybrid Light: uzoq masofali ilg'or texnologiya",
        "LENZ: 4 mm qattiq fokusli linza",
        "Suv va changga chidamli (IP66)",
        "SMATR POE",
      ],
    },

    {
      id: 11,
      img: "./4.jpg",
      title: "4mp FID-S1087k334 4mp",
      optionsen: [
        "METAL BULLET CAMERA",
        "High quality imaging with 4 MP resolution",
        "24/7 colorful imaging",
        "Support Human Body Detection + Dual-Light Intelligent Function,",
        "4mp hd resolution, 2560*1440@25, 2304*1296@25 , 1080P@25",
        "Smart infrared/warm light control, no need photosensitive",
        "Supports Ultra H. 265 intelligent coding",
        "Support Onvif international standard protocol",
        "Support audio input/output 1ch, support two-way audio;support dual-stream",
        "Smart Hybrid Light: advanced technology with long range",
        "LENZ:4mm fixed focal lens",
        "Water and dust resistant (IP66)",
        "SMATR POE",
      ],
      optionsru: [
        "МЕТАЛЛ ПУЛЯ КАМЕРА",
        "Высококачественное изображение с разрешением 4 МП",
        "Цветное изображение 24 часа в сутки, 7 дней в неделю",
        "Поддержка обнаружения человеческого тела + интеллектуальная функция двойного освещения",
        "Разрешение HD 4 Мп, 2560*1440@25, 2304*1296@25, 1080P@25",
        "Интеллектуальное управление инфракрасным/теплым светом, нет необходимости в светочувствительности",
        "Поддержка интеллектуального кодирования Ultra H. 265",
        "Поддержка международного стандартного протокола Onvif",
        "Поддержка 1-канального аудиовхода/выхода, поддержка двустороннего звука, поддержка двухпотокового звука",
        "Умный гибридный свет: передовые технологии с большим радиусом действия",
        "ЛЕНЦ: объектив с фиксированным фокусным расстоянием 4 мм",
        "Водо- и пыленепроницаемость (IP66)",
        "СМАТР ПОЭ",
      ],
      optionsuz: [
        "METAL BULLET KAMERA",
        "4 MP ruxsati bilan yuqori sifatli tasvirlash",
        "24/7 rangli tasvir",
        "Inson tanasini aniqlashni qo'llab-quvvatlash + Ikki nurli aqlli funktsiya,",
        "4mp hd ruxsati, 2560*1440@25, 2304*1296@25, 1080P@25",
        "Aqlli infraqizil/issiq yorug'lik nazorati, fotosensitivlik kerak emas",
        "Ultra H. 265 aqlli kodlashni qo'llab-quvvatlaydi",
        "Onvif xalqaro standart protokolini qo'llab-quvvatlash",
        "1 kanalli audio kirish/chiqishni qo'llab-quvvatlash, ikki tomonlama ovozni qo'llab-quvvatlash; ikki tomonlama oqimni qo'llab-quvvatlash",
        "Smart Hybrid Light: uzoq masofali ilg'or texnologiya",
        "LENZ: 4 mm qattiq fokusli linza",
        "Suv va changga chidamli (IP66)",
        "SMATR POE",
      ],
    },

    {
      id: 12,
      img: "./4.jpg",
      title: "4mp FID-S1087k414 4mp",
      optionsen: [
        "METAL BULLET CAMERA",
        "High quality imaging with 4 MP resolution",
        "24/7 colorful imaging",
        "Flash 8MB,DDR264MB ; single-core A7 1.2GHz",
        "Support Human Body Detection + Dual-Light Intelligent Function,",
        "4mp hd resolution, 2560*1440@25, 2304*1296@25 , 1080P@25",
        "Smart infrared/warm light control, no need photosensitive",
        "Supports Ultra H. 265 intelligent coding*Support Onvif international standard protocol with third-party NVR, Support Uniview and HIK Vision private protocol",
        "Support audio input/output 1ch, support two-way audio;",
        "LENZ:4mm fixed focal lens",
        "Water and dust resistant (IP66)",
        "SMATR POE",
      ],
      optionsru: [
        "МЕТАЛЛ ПУЛЯ КАМЕРА",
        "Высококачественное изображение с разрешением 4 МП",
        "Цветное изображение 24 часа в сутки, 7 дней в неделю",
        "Флэш-память 8 МБ, DDR264 МБ; одноядерный A7 1,2 ГГц",
        "Поддержка обнаружения человеческого тела + интеллектуальная функция двойного освещения",
        "Разрешение HD 4 Мп, 2560*1440@25, 2304*1296@25, 1080P@25",
        "Интеллектуальное управление инфракрасным/теплым светом, нет необходимости в светочувствительности",
        "Поддержка интеллектуального кодирования Ultra H. 265 * Поддержка протокола международного стандарта Onvif со сторонними видеорегистраторами, поддержка частного протокола Uniview и HIK Vision",
        "Поддержка аудиовхода/выхода 1 канал, поддержка двустороннего звука;",
        "ЛЕНЦ: объектив с фиксированным фокусным расстоянием 4 мм",
        "Водо- и пыленепроницаемость (IP66)",
        "СМАТР ПОЭ",
      ],
      optionsuz: [
        "METAL BULLET KAMERA",
        "4 MP ruxsati bilan yuqori sifatli tasvirlash",
        "24/7 rangli tasvir",
        "Flash 8MB, DDR264MB; bir yadroli A7 1.2GHz",
        "Inson tanasini aniqlashni qo'llab-quvvatlash + Ikki nurli aqlli funktsiya,",
        "4mp hd ruxsati, 2560*1440@25, 2304*1296@25, 1080P@25",
        "Aqlli infraqizil/issiq yorug'lik nazorati, fotosensitivlik kerak emas",
        "Ultra H. 265 aqlli kodlashni qo'llab-quvvatlaydi* Onvif xalqaro standart protokolini uchinchi tomon NVR, Support Uniview va HIK Vision shaxsiy protokoli bilan qo'llab-quvvatlaydi",
        "1 kanalli audio kirish/chiqishni qo'llab-quvvatlash, ikki tomonlama ovozni qo'llab-quvvatlash;",
        "LENZ: 4 mm qattiq fokusli linza",
        "Suv va changga chidamli (IP66)",
        "SMATR POE",
      ],
    },

    {
      id: 13,
      img: "./5.jpg",
      title: "5mp FIB-S1085k5 5mp",
      optionsen: [
        "PELASTIC DOME CAMERA",
        "High quality imaging with 5 MP resolution",
        "24/7 colorful imaging",
        "5MP Super Starlight   Progressive Scan CMOS",
        "Support 120dB Optical width dynamic (WDR)   ",
        "two mic",
        "5MP HD Resolution, 2880*1620@25, 2560*1440@25, 2304*1296@25, 1920*1080@25, 1920*1080@30",
        "Support Human Body Detection + Dual-Light Intelligent Function,",
        "Smart infrared/warm light control, no need photosensitive",
        "Supports Ultra H. 265 intelligent coding",
        "Support Onvif international standard protocol with third-party NVR, Support Uniview and HIK Vision private protocol",
        "Support audio input/output 1ch, support two-way audio;Если вам нужна эта опция, вы должны заказать ее",
        "Starlight :Day/Night(ICR)AWB,AGC,BLC,HLC2DNR/3DNR",
        "Smart Hybrid Light: advanced technology with long range",
        "LENZ:4mm fixed focal lens",
        "SMATR POE",
      ],
      optionsru: [
        "ПЛАСТИКОВАЯ КУПОЛЬНАЯ КАМЕРА",
        "Высококачественное изображение с разрешением 5 МП",
        "Цветное изображение 24 часа в сутки, 7 дней в неделю",
        "5 МП Super Starlight CMOS с прогрессивной разверткой",
        "Поддержка динамической оптической ширины 120 дБ (WDR)",
        "два микрофона",
        "Разрешение HD 5 МП, 2880*1620@25, 2560*1440@25, 2304*1296@25, 1920*1080@25, 1920*1080@30",
        "Поддержка обнаружения человеческого тела + интеллектуальная функция двойного освещения",
        "Интеллектуальное управление инфракрасным/теплым светом, нет необходимости в светочувствительности",
        "Поддержка интеллектуального кодирования Ultra H. 265",
        "Поддержка международного стандартного протокола Onvif со сторонними видеорегистраторами, поддержка частного протокола Uniview и HIK Vision",
        "Поддержка 1-канального аудиовхода/вывода, поддержка двусторонней аудиосвязи; если вам нужна эта опция, вы должны заказать ее",
        "Звездный свет: день/ночь (ICR)AWB,AGC,BLC,HLC2DNR/3DNR",
        "Умный гибридный свет: передовые технологии с большим радиусом действия",
        "ЛЕНЦ: объектив с фиксированным фокусным расстоянием 4 мм",
        "СМАТР ПОЭ",
      ],
      optionsuz: [
        "PELASTIC GUMBAL KAMERA",
        "5 MP ruxsati bilan yuqori sifatli tasvirlash",
        "24/7 rangli tasvir",
        "5MP Super Starlight Progressive Scan CMOS",
        "120dB Optik kenglik dinamikini (WDR) qo'llab-quvvatlash",
        "ikki mikrofon",
        "5MP HD ruxsati, 2880*1620@25, 2560*1440@25, 2304*1296@25, 1920*1080@25, 1920*1080@30",
        "Inson tanasini aniqlashni qo'llab-quvvatlash + Ikki nurli aqlli funktsiya,",
        "Aqlli infraqizil/issiq yorug'lik nazorati, fotosensitivlik kerak emas",
        "Ultra H. 265 aqlli kodlashni qo'llab-quvvatlaydi",
        "Onvif xalqaro standart protokolini uchinchi tomon NVR, Support Uniview va HIK Vision shaxsiy protokoli bilan qo'llab-quvvatlash",
        "1ch audio kirish/chiqishni qo'llab-quvvatlash, ikki tomonlama audioni qo'llab-quvvatlash",
        "Yulduzli yorug'lik: kunduz / tun (ICR) AWB, AGC, BLC, HLC2DNR / 3DNR",
        "Smart Hybrid Light: uzoq masofali ilg'or texnologiya",
        "LENZ: 4 mm qattiq fokusli linza",
        "SMATR POE",
      ],
    },

    {
      id: 13,
      img: "./5.jpg",
      title: "4mp FIB-S1085k334 4mp",
      optionsen: [
        "PELASTIC DOME CAMERA",
        "High quality imaging with 4 MP resolution",
        "24/7 colorful imaging",
        "Support Human Body Detection + Dual-Light Intelligent Function,",
        "4mp hd resolution, 2560*1440@25, 2304*1296@25 , 1080P@25",
        "Smart infrared/warm light control, no need photosensitive",
        "Supports Ultra H. 265 intelligent coding",
        "Support Onvif international standard protocol",
        "Support audio input/output 1ch, support two-way audio;support dual-stream",
        "Smart Hybrid Light: advanced technology with long range",
        "LENZ:4mm fixed focal lens",
        "SMATR POE",
      ],
      optionsru: [
        "ПЛАСТИКОВАЯ КУПОЛЬНАЯ КАМЕРА",
        "Высококачественное изображение с разрешением 4 МП",
        "Цветное изображение 24 часа в сутки, 7 дней в неделю",
        "Поддержка обнаружения человеческого тела + интеллектуальная функция двойного освещения",
        "Разрешение HD 4 Мп, 2560*1440@25, 2304*1296@25, 1080P@25",
        "Интеллектуальное управление инфракрасным/теплым светом, нет необходимости в светочувствительности",
        "Поддержка интеллектуального кодирования Ultra H. 265",
        "Поддержка международного стандартного протокола Onvif",
        "Поддержка 1-канального аудиовхода/выхода, поддержка двустороннего звука, поддержка двухпотокового звука",
        "Умный гибридный свет: передовые технологии с большим радиусом действия",
        "ЛЕНЦ: объектив с фиксированным фокусным расстоянием 4 мм",
        "СМАТР ПОЭ",
      ],
      optionsuz: [
        "PELASTIC GUMBAL KAMERA",
        "4 MP ruxsati bilan yuqori sifatli tasvirlash",
        "24/7 rangli tasvir",
        "Inson tanasini aniqlashni qo'llab-quvvatlash + Ikki nurli aqlli funktsiya,",
        "4mp hd ruxsati, 2560*1440@25, 2304*1296@25, 1080P@25",
        "Aqlli infraqizil/issiq yorug'lik nazorati, fotosensitivlik kerak emas",
        "Ultra H. 265 aqlli kodlashni qo'llab-quvvatlaydi",
        "Onvif xalqaro standart protokolini qo'llab-quvvatlash",
        "1 kanalli audio kirish/chiqishni qo'llab-quvvatlash, ikki tomonlama ovozni qo'llab-quvvatlash; ikki tomonlama oqimni qo'llab-quvvatlash",
        "Smart Hybrid Light: uzoq masofali ilg'or texnologiya",
        "LENZ: 4 mm qattiq fokusli linza",
        "SMATR POE",
      ],
    },

    {
      id: 14,
      img: "./5.jpg",
      title: "4mp FIB-S1085k414 4mp",
      optionsen: [
        "PELASTIC DOME CAMERA",
        "High quality imaging with 4 MP resolution",
        "24/7 colorful imaging",
        "Flash 8MB,DDR264MB ; single-core A7 1.2GHz",
        "Support Human Body Detection + Dual-Light Intelligent Function,",
        "4mp hd resolution, 2560*1440@25, 2304*1296@25 , 1080P@25",
        "Smart infrared/warm light control, no need photosensitive",
        "Supports Ultra H. 265 intelligent coding*Support Onvif international standard protocol with third-party NVR, Support Uniview and HIK Vision private protocol",
        "Support audio input/output 1ch, support two-way audio;Если вам нужна эта опция, вы должны заказать ее",
        "LENZ:4mm fixed focal lens",
        "SMATR POE",
      ],
      optionsru: [
        "ПЛАСТИКОВАЯ КУПОЛЬНАЯ КАМЕРА",
        "Высококачественное изображение с разрешением 4 МП",
        "Цветное изображение 24 часа в сутки, 7 дней в неделю",
        "Флэш-память 8 МБ, DDR264 МБ; одноядерный A7 1,2 ГГц",
        "Поддержка обнаружения человеческого тела + интеллектуальная функция двойного освещения",
        "Разрешение HD 4 Мп, 2560*1440@25, 2304*1296@25, 1080P@25",
        "Интеллектуальное управление инфракрасным/теплым светом, нет необходимости в светочувствительности",
        "Поддержка интеллектуального кодирования Ultra H. 265 * Поддержка протокола международного стандарта Onvif со сторонними видеорегистраторами, поддержка частного протокола Uniview и HIK Vision",
        "Поддержка 1-канального аудиовхода/вывода, поддержка двусторонней аудиосвязи; если вам нужна эта опция, вы должны заказать ее",
        "ЛЕНЦ: объектив с фиксированным фокусным расстоянием 4 мм",
        "СМАТР ПОЭ",
      ],
      optionsuz: [
        "PELASTIC GUMBAL KAMERA",
        "4 MP ruxsati bilan yuqori sifatli tasvirlash",
        "24/7 rangli tasvir",
        "Flash 8MB, DDR264MB; bir yadroli A7 1.2GHz",
        "Inson tanasini aniqlashni qo'llab-quvvatlash + Ikki nurli aqlli funktsiya,",
        "4mp hd ruxsati, 2560*1440@25, 2304*1296@25, 1080P@25",
        "Aqlli infraqizil/issiq yorug'lik nazorati, fotosensitivlik kerak emas",
        "Ultra H. 265 aqlli kodlashni qo'llab-quvvatlaydi* Onvif xalqaro standart protokolini uchinchi tomon NVR, Support Uniview va HIK Vision shaxsiy protokoli bilan qo'llab-quvvatlaydi",
        "1ch audio kirish/chiqishni qo'llab-quvvatlash, ikki tomonlama audioni qo'llab-quvvatlash",
        "LENZ: 4 mm qattiq fokusli linza",
        "SMATR POE",
      ],
    },

    {
      id: 15,
      img: "./6.jpg",
      title: "5mp FID-S1086k5 5mp",
      optionsen: [
        "METAL BULLET CAMERA",
        "High quality imaging with 5 MP resolution",
        "24/7 colorful imaging",
        "5MP Super Starlight   Progressive Scan CMOS",
        "Support 120dB Optical width dynamic (WDR)   ",
        "two mic",
        "5MP HD Resolution, 2880*1620@25, 2560*1440@25, 2304*1296@25, 1920*1080@25, 1920*1080@30",
        "Support Human Body Detection + Dual-Light Intelligent Function,",
        "Smart infrared/warm light control, no need photosensitive",
        "Supports Ultra H. 265 intelligent coding",
        "Support Onvif international standard protocol with third-party NVR, Support Uniview and HIK Vision private protocol",
        "Support audio input/output 1ch, support two-way audio;",
        "Starlight :Day/Night(ICR)AWB,AGC,BLC,HLC2DNR/3DNR",
        "Smart Hybrid Light: advanced technology with long range",
        "LENZ:4mm fixed focal lens",
        "Water and dust resistant (IP66)",
        "SMATR POE",
      ],
      optionsru: [
        "МЕТАЛЛ ПУЛЯ КАМЕРА",
        "Высококачественное изображение с разрешением 5 МП",
        "Цветное изображение 24 часа в сутки, 7 дней в неделю",
        "5 МП Super Starlight CMOS с прогрессивной разверткой",
        "Поддержка динамической оптической ширины 120 дБ (WDR)",
        "два микрофона",
        "Разрешение HD 5 МП, 2880*1620@25, 2560*1440@25, 2304*1296@25, 1920*1080@25, 1920*1080@30",
        "Поддержка обнаружения человеческого тела + интеллектуальная функция двойного освещения",
        "Интеллектуальное управление инфракрасным/теплым светом, нет необходимости в светочувствительности",
        "Поддержка интеллектуального кодирования Ultra H. 265",
        "Поддержка международного стандартного протокола Onvif со сторонними видеорегистраторами, поддержка частного протокола Uniview и HIK Vision",
        "Поддержка аудиовхода/выхода 1 канал, поддержка двустороннего звука;",
        "Звездный свет: день/ночь (ICR)AWB,AGC,BLC,HLC2DNR/3DNR",
        "Умный гибридный свет: передовые технологии с большим радиусом действия",
        "ЛЕНЦ: объектив с фиксированным фокусным расстоянием 4 мм",
        "Водо- и пыленепроницаемость (IP66)",
        "СМАТР ПОЭ",
      ],
      optionsuz: [
        "METAL BULLET KAMERA",
        "5 MP ruxsati bilan yuqori sifatli tasvirlash",
        "24/7 rangli tasvir",
        "5MP Super Starlight Progressive Scan CMOS",
        "120dB Optik kenglik dinamikini (WDR) qo'llab-quvvatlash",
        "ikki mikrofon",
        "5MP HD ruxsati, 2880*1620@25, 2560*1440@25, 2304*1296@25, 1920*1080@25, 1920*1080@30",
        "Inson tanasini aniqlashni qo'llab-quvvatlash + Ikki nurli aqlli funktsiya,",
        "Aqlli infraqizil/issiq yorug'lik nazorati, fotosensitivlik kerak emas",
        "Ultra H. 265 aqlli kodlashni qo'llab-quvvatlaydi",
        "Onvif xalqaro standart protokolini uchinchi tomon NVR, Support Uniview va HIK Vision shaxsiy protokoli bilan qo'llab-quvvatlash",
        "1 kanalli audio kirish/chiqishni qo'llab-quvvatlash, ikki tomonlama ovozni qo'llab-quvvatlash;",
        "Yulduzli yorug'lik: kunduz / tun (ICR) AWB, AGC, BLC, HLC2DNR / 3DNR",
        "Smart Hybrid Light: uzoq masofali ilg'or texnologiya",
        "LENZ: 4 mm qattiq fokusli linza",
        "Suv va changga chidamli (IP66)",
        "SMATR POE",
      ],
    },

    {
      id: 16,
      img: "./6.jpg",
      title: "4mp FID-S1086k414 4mp",
      optionsen: [
        "METAL BULLET CAMERA",
        "High quality imaging with 4 MP resolution",
        "24/7 colorful imaging",
        "Flash 8MB,DDR264MB ; single-core A7 1.2GHz",
        "Support Human Body Detection + Dual-Light Intelligent Function,",
        "4mp hd resolution, 2560*1440@25, 2304*1296@25 , 1080P@25",
        "Smart infrared/warm light control, no need photosensitive",
        "Supports Ultra H. 265 intelligent coding*Support Onvif international standard protocol with third-party NVR, Support Uniview and HIK Vision private protocol",
        "Support audio input/output 1ch, support two-way audio;Если вам нужна эта опция, вы должны заказать ее",
        "LENZ:4mm fixed focal lens",
        "Water and dust resistant (IP66)",
        "SMATR POE",
      ],
      optionsru: [
        "МЕТАЛЛ ПУЛЯ КАМЕРА",
        "Высококачественное изображение с разрешением 4 МП",
        "Цветное изображение 24 часа в сутки, 7 дней в неделю",
        "Флэш-память 8 МБ, DDR264 МБ; одноядерный A7 1,2 ГГц",
        "Поддержка обнаружения человеческого тела + интеллектуальная функция двойного освещения",
        "Разрешение HD 4 Мп, 2560*1440@25, 2304*1296@25, 1080P@25",
        "Интеллектуальное управление инфракрасным/теплым светом, нет необходимости в светочувствительности",
        "Поддержка интеллектуального кодирования Ultra H. 265 * Поддержка протокола международного стандарта Onvif со сторонними видеорегистраторами, поддержка частного протокола Uniview и HIK Vision",
        "Поддержка 1-канального аудиовхода/вывода, поддержка двусторонней аудиосвязи; если вам нужна эта опция, вы должны заказать ее",
        "ЛЕНЦ: объектив с фиксированным фокусным расстоянием 4 мм",
        "Водо- и пыленепроницаемость (IP66)",
        "СМАТР ПОЭ",
      ],
      optionsuz: [
        "METAL BULLET KAMERA",
        "4 MP ruxsati bilan yuqori sifatli tasvirlash",
        "24/7 rangli tasvir",
        "Flash 8MB, DDR264MB; bir yadroli A7 1.2GHz ",
        "Inson tanasini aniqlashni qo'llab-quvvatlash + Ikki nurli aqlli funktsiya,",
        "4mp hd ruxsati, 2560*1440@25, 2304*1296@25, 1080P@25",
        "Aqlli infraqizil/issiq yorug'lik nazorati, fotosensitivlik kerak emas",
        "Ultra H. 265 aqlli kodlashni qo'llab-quvvatlaydi* Onvif xalqaro standart protokolini uchinchi tomon NVR, Support Uniview va HIK Vision shaxsiy protokoli bilan qo'llab-quvvatlaydi",
        "1ch audio kirish/chiqishni qo'llab-quvvatlash, ikki tomonlama audioni qo'llab-quvvatlash",
        "LENZ: 4 mm qattiq fokusli linza",
        "Suv va changga chidamli (IP66)",
        "SMATR POE",
      ],
    },

    {
      id: 17,
      img: "./6.jpg",
      title: "FAB-184o5 5mp",
      optionsen: [
        "AHD METAL BULLET CAMERA",
        "High quality imaging with 5 MP resolution",
        "24/7 colorful imaging",
        "Starlight :Day/Night",
        "One port for four switchable signals (TVI/AHD/CVI/CVBS）",
        "LENZ:4mm fixed focal lens",
        "High quality audio with audio over coaxial cable, built-in mic",
        "Water and dust resistant (IP66)",
        "12v DC",
      ],
      optionsru: [
        "AHD МЕТАЛЛИЧЕСКАЯ ПУЛЕВАЯ КАМЕРА",
        "Высококачественное изображение с разрешением 5 МП",
        "Цветное изображение 24 часа в сутки, 7 дней в неделю",
        "Звездный свет: День/Ночь",
        "Один порт для четырех переключаемых сигналов (TVI/AHD/CVI/CVBS）)",
        "ЛЕНЦ: объектив с фиксированным фокусным расстоянием 4 мм",
        "Высококачественный звук по коаксиальному кабелю, встроенный микрофон",
        "Водо- и пыленепроницаемость (IP66)",
        "12 В постоянного тока",
      ],
      optionsuz: [
        "AHD METAL BULLET KAMERA",
        "5 MP ruxsati bilan yuqori sifatli tasvirlash",
        "24/7 rangli tasvir",
        "Yulduzli yorug'lik: kunduz / tun",
        "To'rtta almashtiriladigan signallar uchun bitta port (TVI/AHD/CVI/CVBS）)",
        "LENZ: 4 mm qattiq fokusli linza",
        "Koaksiyal kabel orqali audio bilan yuqori sifatli audio, o'rnatilgan mikrofon",
        "Suv va changga chidamli (IP66)",
        "12v DC",
      ],
    },

    {
      id: 18,
      img: "./5.jpg",
      title: "FAB-185o5 5mp",
      optionsen: [
        "AHD PELASTIC DOME CAMERA",
        "High quality imaging with 5 MP resolution",
        "24/7 colorful imaging",
        "Starlight :Day/Night",
        "One port for four switchable signals (TVI/AHD/CVI/CVBS）",
        "LENZ:4mm fixed focal lens",
        "High quality audio with audio over coaxial cable, built-in micЕсли вам нужна эта опция, вы должны заказать ее",
        "12v DC",
      ],
      optionsru: [
        "AHD ПЛАСТИКОВАЯ КУПОЛЬНАЯ КАМЕРА",
        "Высококачественное изображение с разрешением 5 МП",
        "Цветное изображение 24 часа в сутки, 7 дней в неделю",
        "Звездный свет: День/Ночь",
        "Один порт для четырех переключаемых сигналов (TVI/AHD/CVI/CVBS",
        "ЛЕНЦ: объектив с фиксированным фокусным расстоянием 4 мм",
        "Высококачественный звук по коаксиальному кабелю, встроенный микрофон. Если вам нужна эта опция, вы должны заказать ее",
        "12 В постоянного тока",
      ],
      optionsuz: [
        "AHD PELASTIC GUMBAL KAMERA",
        "5 MP ruxsati bilan yuqori sifatli tasvirlash",
        "24/7 rangli tasvir",
        "Yulduzli yorug'lik: kunduz / tun",
        "To'rtta almashtiriladigan signallar uchun bitta port (TVI/AHD/CVI/CVBS)",
        "LENZ: 4 mm qattiq fokusli linza",
        "Koaksial kabel orqali audio bilan yuqori sifatli audio, o'rnatilgan micEsli vam nojna eta variant, vy doljny zakazat ee",
        "12v DC",
      ],
    },

    {
      id: 19,
      img: "./3.jpg",
      title: "FAD-S187o5 5mp",
      optionsen: [
        "AHD METAL BULLET CAMERA",
        "High quality imaging with 5 MP resolution",
        "24/7 colorful imaging",
        "Starlight :Day/Night",
        "One port for four switchable signals (TVI/AHD/CVI/CVBS）",
        "LENZ:4mm fixed focal lens",
        "High quality audio with audio over coaxial cable, built-in mic",
        "Water and dust resistant (IP66)",
        "12v DC",
      ],
      optionsru: [
        "AHD МЕТАЛЛИЧЕСКАЯ ПУЛЕВАЯ КАМЕРА",
        "Высококачественное изображение с разрешением 5 МП",
        "Цветное изображение 24 часа в сутки, 7 дней в неделю",
        "Звездный свет: День/Ночь",
        "Один порт для четырех переключаемых сигналов (TVI/AHD/CVI/CVBS",
        "ЛЕНЦ: объектив с фиксированным фокусным расстоянием 4 мм",
        "Высококачественный звук по коаксиальному кабелю, встроенный микрофон",
        "Водо- и пыленепроницаемость (IP66)",
        "12 В постоянного тока",
      ],
      optionsuz: [
        "AHD METAL BULLET KAMERA",
        "5 MP ruxsati bilan yuqori sifatli tasvirlash",
        "24/7 rangli tasvir",
        "Yulduzli yorug'lik: kunduz / tun",
        "To'rtta almashtiriladigan signallar uchun bitta port (TVI/AHD/CVI/CVBS)",
        "LENZ: 4 mm qattiq fokusli linza",
        "Koaksial kabel orqali audio bilan yuqori sifatli audio, o'rnatilgan mikrofon",
        "Suv va changga chidamli (IP66)",
        "12v DC",
      ],
    },
  ]);

  return { switches, cameras };
});
